keys:
  - &avass age19k67f8muz2n368y2n0k55wr8z0d6q9vhh22v5re5c692v3x3af9qwsnu6a
  - &vcc age102ndpvqhfg5lpdfr70nxupu8a6t422509c5fsxmq502dff8d0yxq83ygkx
creation_rules:
  - path_regex: ^home-manager/modules/vcc/secrets.yaml$
    key_groups:
    - age:
        - *vcc
        - *avass
  - key_groups:
    - age:
        - *avass
