on:
  push:
    branches: [main]

jobs:
  lints:
    name: Build and push
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setup netrc
      run: |
        echo "machine attic.albinvass.se" >> /tmp/netrc
        echo "password ${{ secrets.ATTIC_TOKEN }}" >> /tmp/netrc

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = https://attic.albinvass.se/nixos https://cache.nixos.org
          trusted-public-keys = nixos:9P6IFV7gsoidt0pX9w1R4CYZKFkvnsU6UGxvzYvcfMg= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          netrc-file = /tmp/netrc

    - name: Build homeConfiguration
      run: nix build .#homeConfigurations."avass@5CG0388QDR".activationPackage

    - name: Push to attic
      run: |
        nix develop --command attic login attic https://attic.albinvass.se ${{ secrets.ATTIC_TOKEN }}
        nix develop --command attic push nixos ./result
